/*
* SYSLOGLOGGER.CPP                    Copyright (c) 2010, Ilmatieteen laitos
*
* With syslogger, one can log into:
*   - files
*   - system console
*   - any external processes (pipes)
*   - email
*   - other machines with 'syslogd' running
*
* Note: ONLY ONE SYSLOG SESSION PER PROCESS seems to be allowed by the API.
*       If we use syslog within a service, NO OTHER PLUGIN (or the service itself)
*       may use it!     --AKa 14-Jan-10
*
* Note: THERE IS NO ERROR DETECTION about whether the logs actually get written
*       (i.e. having wrong file permissions at '/var/log' will silently lose
*       all logs)
*
* Syslog seems to be best adopted for web logging (and maybe only web logging).
*
* Ref: <http://www.linode.com/wiki/index.php/Syslog_Howto>
*      'man 3 syslog'
*/
#include "SyslogLogger.h"

#include <syslog.h>

#include <string>
#include <cstring>
#include <stdexcept>

using namespace std;

/*
* 'facility':
    "daemon":   LOG_DAEMON      "Other daemon programs without a facility of their own"
    "user":     LOG_USER        "Messages generated by random user processes. Default."
    "local0".."local7": LOG_LOCAL0..7 "Reserved for local use."

  Note: Facility values are system specific, and we cannot rely on them (or have the
        configuration file give us integers). Also,
*/
SyslogLogger::SyslogLogger(const char *facility)
{
  int fac = (strcmp(facility, "daemon") == 0)
                ? LOG_DAEMON
                : (strcmp(facility, "user") == 0)
                      ? LOG_USER
                      : (strcmp(facility, "local0") == 0)
                            ? LOG_LOCAL0
                            : (strcmp(facility, "local1") == 0)
                                  ? LOG_LOCAL1
                                  : (strcmp(facility, "local2") == 0)
                                        ? LOG_LOCAL2
                                        : (strcmp(facility, "local3") == 0)
                                              ? LOG_LOCAL3
                                              : (strcmp(facility, "local4") == 0)
                                                    ? LOG_LOCAL4
                                                    : (strcmp(facility, "local5") == 0)
                                                          ? LOG_LOCAL5
                                                          : (strcmp(facility, "local6") == 0)
                                                                ? LOG_LOCAL6
                                                                : (strcmp(facility, "local7") == 0)
                                                                      ? LOG_LOCAL7
                                                                      : -1;

  if (fac < 0)
  {
    throw E_LOG_FATAL("Bad syslog facility: %s", facility);
  }

  // 'id' param of 'openlog()' is probably stored AS IS - must be string constant
  // or static buffer.
  //
  static const char *id =
#ifdef RPM_VERSION
#define _QUOTE(x) #x
      "q3-" _QUOTE(RPM_VERSION)
#else
      "q3"
#endif
      ;

  // There is no handler to our logging - seems 'syslog' takes the process
  // id (which kind of sucks - will clash with any other code writing to
  // syslog under the same server).
  //
  openlog(id, 0 /*flags*/, fac);
}

/*
*/
void SyslogLogger::log(enum category cat,
                       const char *file,
                       unsigned line,
                       const Logger::unique_t id,
                       const char *msg,
                       size_t msg_len)
{
  if (!msg)
    return;

  int prio = -1;
  switch (cat)
  {
    // LOG_EMERG;   // "system is unusable"
    // LOG_ALERT;   // "action must be taken immediately"
    case _FATAL:
      prio = LOG_CRIT;
      break;  // "critical conditions"
    case _ERROR:
      prio = LOG_ERR;
      break;  // "error conditions"
    case _WARNING:
      prio = LOG_WARNING;
      break;  // "warning conditions"
              // LOG_NOTICE   // "normal, but significant conditions"
    case _INFO:
      prio = LOG_INFO;
      break;  // "informational message"
    case _DEBUG:
      prio = LOG_DEBUG;
      break;

    // The following don't have a 1:1 category in syslog:
    //
    case _BUG:
      prio = LOG_ERR;
      break;
    case _USAGE:
      prio = LOG_NOTICE;
      break;
    case _TIMING:
      prio = LOG_DEBUG;
      break;
    case _LUA:
      prio = LOG_DEBUG;
      break;
    case _STAT:
      prio = LOG_INFO;
      break;

    // MAINTENANCE uses same syslog level as FATAL but is normal to occur
    // (i.e. server startup); may cause email announcements (depends on syslog config)
    //
    case _MAINTENANCE:
      prio = LOG_CRIT;
      break;
  }

  // We don't need source file and line info on syslog.
  //
  (void)file;
  (void)line;

  // Do NOT use 'string_fmt()' on 'msg' - may truncate it (it can be REALLY LONG, i.e. from user
  // script 'DUMP()')
  //
  string tmp = string_fmt("[%lld]\n", (long long)id);
  size_t len = msg_len + 1 + tmp.length();

  char buf[len + 1];
  {
    memcpy(buf, msg, msg_len);
    buf[msg_len] = ' ';
    strcpy(buf + msg_len + 1, tmp.c_str());  // adds the terminating '\0'

    syslog(prio, buf);  // atomic
  }
}
