#
# SConstruct for building loadable Lua module for command line usage
#
# Notes:
#	Use CPPFLAGS instead of CXXFLAGS (or figure out, why '-W...' and '-O...' don't get
#	through as CXXFLAGS.
#
# Dependencies:
#   Newbase     (needed to access SQD files)
#       libz
#       libbz2
#       libpng
#       libjpeg
#       Boost 1.4x
#   Tron        (needed for creating curves)
#   libproj
#   liblua
#
# Platforms:
#   Linux 64-bit (tested on Centos, Ubuntu 9.10)
#   Linux 32-bit (not regularily tested, but fix if there are issues reported)
#
# Change log:
#       AKa ...: Renamed 'metqu/'
#       AKa 30-Apr-2010: Moved to 'standalone/' - away from server codes
#
import os
import sys
import re

# Lua module
#
LUA51_METQU_SO="lua51-metqu.so"

LUA51_METQU_NOSQD_SO="lua51-metqu_nosqd.so"

Help(""" 
    Usage: scons [-j4] [-Q] [debug=1] [sse=0] [objdir=<path>]"""+ LUA51_METQU_SO+"|"+LUA51_METQU_NOSQD_SO+"""
    
    Or just use 'make release|debug', which point right back to us.
""") 

Decider("MD5-timestamp") 

DEBUG=      int( ARGUMENTS.get("debug", 0) ) != 0
RELEASE=    not DEBUG

VARIANT= "debug"
if RELEASE:
    VARIANT= "release"

TOOLS_PATH= "../tools"
COMMON_PATH= "../common"
ADDONS_PATH= "../addons"

# bin2c.lua and LuaNew can come either from '../tools/' (in RPM packaging) 
# or from '../addons/newcairo/tools' (in development)
#
BIN2C_LUA=   TOOLS_PATH+"/bin2c.lua"
if not os.path.exists(BIN2C_LUA):
	BIN2C_LUA= "../addons/newcairo/tools/bin2c.lua"

LUANEW_PATH= TOOLS_PATH+"/luanew"
if not os.path.exists(LUANEW_PATH):
	LUANEW_PATH= "../addons/newcairo/tools/luanew"

# Juha uses 32-bit Ubuntu that has some details different from 64-bit Centos.
#
UNAME_A= os.popen("uname -a").read()
UBUNTU= UNAME_A.find("Ubuntu") >= 0

# Note: Use of '.strip()' takes away a trailing newline.
#
UNAME_M = os.popen("uname -m").read().strip()
LINUX32= (UNAME_M=="i686")     # or "x86_64"

LIB_PREFIX= LINUX32 and "/usr/lib/" \
                     or "/usr/lib64/"

# Optimize matrix operations for SSE (requires a recent CPU, see <http://en.wikipedia.org/wiki/SSE3>)
#
SSE=        int( ARGUMENTS.get("sse", 1) ) != 0

OBJDIR=     ARGUMENTS.get("objdir","obj")
PREFIX=     "/usr"

env= Environment( LIBPREFIX="" )

LINUX= env["PLATFORM"]=="posix"
OSX= env["PLATFORM"]=="darwin"

# Automatic detection (system first, local if not found):
#
SYSTEM_NEWBASE= os.path.exists(PREFIX+"/include/smartmet/newbase")

SYSTEM_TRON= os.path.exists(PREFIX+"/include/smartmet/tron")

#---
# Base path for IL/KAP git checkout (having local Newbase):
#
GIT_BASE=os.getenv("HOME")+"/git"  # Asko's personal

#---
# OS X fink had confusion finding the right (fink) pkg-config
#
if OSX:
	PKG_CONFIG= "/sw64/bin/pkg-config"
else:
    PKG_CONFIG= "pkg-config"

env.Append( 
    CPPPATH= [ "./include",
               COMMON_PATH+"/include",
               OBJDIR,          # for the .lch files
               LUANEW_PATH+"/include",
               PREFIX+"/include/cairo",
	       PREFIX+"/include/boost169",
               ADDONS_PATH+"/newcairo/include",
             ],

    CPPDEFINES= [ 
        "UNIX",     # Newbase headers require it
        "METQU",
        # "MQD_ENABLED",  # MQD file format
        "USE_NEWBASE",    # 06-Feb-2012 PKi
        ],

    CPPFLAGS= [
        # MAINFLAGS ('-fPIC' is included by default, for SharedObjects)
        #
        "-rdynamic",
        "-Wall",
        "-W",
        "-Wno-unused-parameter",
        
        # 14-Jan-2014 PKi: For new std (auto) and including precompiled lua chunks
        #
        "-std=c++0x",
	    "-fno-signed-char",

	    # DIFFICULTFLAGS (flags that cause some choking, would be good but not used)
	    #
	    #"-Weffc++",
	    #"-Wunreachable-code",
	    #"-Wshadow",
    ],
    )

env.Append( LIBS= [ "proj", "pthread" ] )

#---
# Lua 5.1.x (via 'pkg-config')
#
# Ubuntu has 'lua5.1' on pkg-config (and allows multiple versions to coexist)
# Others have 'lua'
#
if os.system( PKG_CONFIG+" --exists lua5.1" )==0:
    env.ParseConfig( PKG_CONFIG+" --cflags --libs lua5.1" )
else:
    env.ParseConfig( PKG_CONFIG+" --cflags --libs lua" )

#
# SSE optimizations (matrix operations)
#
# NOTE: 'crash.fmi.fi' only has 'sse2' (see '/proc/cpuinfo'). That is okay, SSE3 and
#       later don't really offer much to us.
#
if SSE:
    env.Append( CPPFLAGS=[ 
                    "-mfpmath=sse", 
                    "-msse2" ] )

#
# Debug settings
#
if DEBUG:
    env.Append( CPPFLAGS=[ "-O0", "-g", "-Werror",

        # EXTRAFLAGS (for 'debug' target)
        #
	   "-Wcast-align",
	   "-Wcast-qual",
	   "-Winline",
	   "-Wno-multichar",
	   "-Wno-pmf-conversions",
	   "-Woverloaded-virtual",
	   "-Wpointer-arith",
	   "-Wredundant-decls",
	   "-Wsign-promo",
	   "-Wwrite-strings",

	   #"-Wold-style-cast",
	   #"-ansi", 
	   #"-pedantic",
    ] )

else:
    env.Append( CPPDEFINES="NDEBUG",
                CPPFLAGS= ["-O2", 
                           "-fomit-frame-pointer",

                # RELEASEFLAGS
                #
                "-Wuninitialized",
    ] )

#---
# luac -o - source/prepare.lua          Makes precompiled (binary) Lua bytecode
# lua bin2c.lua -o objs/prepare.lch     Packs the binary into C char array
#
# Note: '-o -' will only work on Unix-like systems (not Windows). Windows
#       needs to use a temporary file since it's stdout is not binary.
#
env["BUILDERS"]["LuaPrecompiled"]= Builder( action = "luac -o - $SOURCE | lua "+BIN2C_LUA+" -o $TARGET") 

for fn in Glob(COMMON_PATH+"/lua/*.lua") + Glob(LUANEW_PATH+"/lua/*.lua") + [TOOLS_PATH+"/assert.lua", TOOLS_PATH+"/type.lua"]:
    s= os.path.basename( str(fn) )
    env.LuaPrecompiled( OBJDIR+"/"+ s.replace(".lua",".lch"), fn ) 


#---
# This much is enough if FMI libraries are not needed.
#
env_nosqd= env.Clone()

# Flags that we cannot use if reading Newbase headers
#
env_nosqd.Append( CPPFLAGS=[
                    "-Wconversion",    # too much of these issues in Newbase headers
                ] )

#---
# Newbase (take it from cvs if not installed into system)
#
# Note: DO NOT use 'smartmet_newbase-mt'; we don't need the locks and it can be damn sloooooooooooow.
#
env.Append( CPPDEFINES= ["USE_NEWBASE"] )
if SYSTEM_NEWBASE:
    # Use 'File()' to take in the file directly without prefix/postfix (which
    # would bring in a shared object, though there are none)    --AKa 24-Jan-10
    #
    env.Append( CPPPATH= [ PREFIX+"/include/smartmet/newbase" ],
                LIBS=   ['smartmet-newbase'] )
else:
    env.Append( CPPPATH= [ GIT_BASE+"/newbase/include" ],
                LIBS=   File(GIT_BASE+"/newbase/libsmartmet_newbase.so")
              )

#---
# Tron (take it from system, if not installed then from cvs)
#
env.Append( CPPDEFINES= [ "USE_TRON" ] )
if SYSTEM_TRON:
    env.Append( CPPPATH= [ PREFIX+"/include/smartmet/tron" ],
                LIBS= [ File( LIB_PREFIX+"libsmartmet-tron.a") ]
              )
else:
    env.Append( CPPPATH= [ GIT_BASE+"/tron/include" ],
                LIBS= ["smartmet-tron"],
                LIBPATH= [ GIT_BASE+"/tron/" ]
              )

#---
# Other libraries (needed for Newbase)
#
# 01-Feb-2012 PKi: Added cairo
#
env.Append( LIBS= [ "png", "jpeg", "z", "bz2", "cairo" ] )

#
# Boost
# 
# NOTE: This must be AFTER NEWBASE that need it (says Mika).
#
# The FMI/KAP policy is to link towards the STATIC libraries and not the SHARED ones,
# due to some Boost binary interface problems (Mika knows more).
#
# 'File()' is needed to add the name as-is, without prefixes ("lib") or postfixes (".so").
#
# Since 1.41 (or somewhere between 1.36 and it) the "-mt" suffix was removed - all
# libraries are the multithreaded versions now (says Mika).
#
# Dynamic versions used when building METQU (normally on Ubuntu 9.10)
#
# 14-Jan-2014 PKi: boost -mt libs
# 14-Jan-2015 PKi: boost 'non' -mt libs
#
mt= UBUNTU and "-mt" or ""
env.Append( LIBPATH= LIB_PREFIX+ "/boost169",
            LIBS= [ "boost_filesystem"+mt, "boost_iostreams"+mt, "boost_regex"+mt, "boost_system"+mt ]
        )

objs= []
nosqd_objs= []

for fn in Glob("source/*.cpp") + Glob(COMMON_PATH+"/source/*.cpp") + Glob(LUANEW_PATH+"/source/*.cpp"):
    s= os.path.basename( str(fn) )
    if (not SSE) and (s=="SSE.cpp"):
        {}  # skip
    else:
        objs += env.SharedObject( OBJDIR+"/1/"+VARIANT+"/"+ s.replace(".cpp",""), fn ) 
        if (not re.search( r'^SQD_', s )) and (not re.search( r'_Tron', s )):
            nosqd_objs += env_nosqd.SharedObject( OBJDIR+"/2/"+VARIANT+"/"+ s.replace(".cpp",""), fn )

out= env.SharedLibrary( LUA51_METQU_SO, objs )

out_nosqd= env_nosqd.SharedLibrary( LUA51_METQU_NOSQD_SO, nosqd_objs )
